version: '3.4'

networks:
  mongo-network:
    external:
      name: mongo-network

volumes:
  mongodata:

services:
  mongodb-server:
    image: mongo:latest
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.hostname == vm08
    volumes:
       - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
       mongo-network:
        aliases:
        - mongodb-server

  econtractapp:
    image:
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - node.hostname == vm08
    ports:
      - "5555:5000"
    networks:
       mongo-network:
        aliases:
        - econtractapp
